sudo: required
services:
  - docker

before_install:
  - docker built -t jorakhachatryan/docker-react-aws -f Dockerfile.dev .

script:
  - docker run -e CI=true jorakhachatryan/docker-react-aws npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "react-docker-ci"
  env: "ReactDockerCi-env"
  bucket_name: "elasticbeanstalk-us-east-2-287663536973"
  bucket_path: "react-docker-ci"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
